### ISSUE TITLE
Support Build Arg to Override Default requirements.txt

### ISSUE THREAD

**Issue by derks** [docker-library/python#188]
The standard for Python+PIP is a `requirements.txt` obviously, however in my use case for a project  there are officially no required dependencies, but you can optionally install extensions that might have external dependencies.  Therefore you end up with an official `requirements.txt` that is empty, but also a `requirements-dev.txt` that has all the optional requirements for development only.

It would be a minor change to set this as a build time arg, and not introduce any backward compatibility issues.

```
ARG REQUIREMENTS_FILE=requirements.txt
ONBUILD COPY $REQUIREMENTS_FILE /usr/src/app/
```

And then us outliers could utilize it:

```bash
$ docker build --build-arg REQUIREMENTS_FILE=requirements_dev.txt ...
```

Or more realistically, this will be from a development focused `docker-compose.yml`:

```yaml
version: "3"
services:
    myapp:
        image: myapp:dev
        build:
            context: .
            args:
                REQUIREMENTS_FILE=requirements-dev.txt
        volumes:
            - .:/usr/src/app
```
