### ISSUE TITLE
docker-compose build hang cause pip install never ends

### ISSUE THREAD

**Issue by MkLHX** [docker-library/python#562]
Hello, i'm trying to build a arm32v7/python docker container using 3.8-slim-buster image and docker-compose build.
The pip install never ends and hang the container build i get this from logs:

```
  Building wheel for numpy (PEP 517): started
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
```

I'm working on raspberry pi IOT project and i get this issue only on docker container build...

Somebody have an idea about that?

**Comment by wglambert** [comment]
Are you installing from https://pypi.org/project/numpy/ or https://www.piwheels.org/project/numpy/
How long have you let it build for?

Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by MkLHX** [comment]
Hi thanks for your answer.

I don't install numpy by myself because it's a dependency from an other package i used.

The app is dockerized and only stuck when i build it on RPI 4B / RPI 3A+, i wait about 30/40min and i stop the script by using CTRL+C because it's never ends or maybe after 1-1h30.

i'm looking for emulation package to allow image build on other support than RPI to faster build.

My Dockerfile
```
FROM arm32v7/python:3.8-slim-buster

RUN apt-get -q update && apt-get -qy install python3-dev 

WORKDIR /WaterSensor/

ARG SERVER_TYPE
ARG SECRET_KEY
ARG DJANGO_ALLOWED_HOSTS
ARG DJANGO_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG GREENPONIK_JSON_LOGIN_ENTRYPOINT_URL
ARG GREENPONIK_CHECK_API_OPEN_URL
ARG USER_PATH
ARG AP_STA_PATH

# caching the requirements installation
COPY ./django_app/requirements.txt requirements.txt

RUN python -m pip -q install -r requirements.txt

COPY ./django_app /WaterSensor/

EXPOSE $DJANGO_PORT

CMD ["bash", "bin/django-start"]

```
docker-compose
```
  django:
    privileged: true
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - APP_TITLE=${APP_TITLE}
        - AP_STA_PATH=${AP_STA_PATH}
        - DB_HOST=${DB_HOST}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - DJANGO_PORT=${DJANGO_PORT}
        - GREENPONIK_CHECK_API_OPEN_URL=${GREENPONIK_CHECK_API_OPEN_URL}
        - GREENPONIK_JSON_LOGIN_ENTRYPOINT_URL=${GREENPONIK_JSON_LOGIN_ENTRYPOINT_URL}
        - NGINX_HOST=${NGINX_HOST}
        - NGINX_PORT=${NGINX_PORT}
        - PROJECT_NAME=${PROJECT_NAME}
        - SECRET_KEY=${SECRET_KEY}
        - SERVER_TYPE=${SERVER_TYPE}
        - USER_PATH=${USER_PATH}
        - VERSION=${VERSION}
    hostname: django
    working_dir: /WaterSensor/
    volumes:
      - /django_app/django.sock:/var/run/django.sock
      - ./django_app/:/WaterSensor/
      - ./django_app/static/:/WaterSensor/static/
      - ./django_app/media/:/WaterSensor/media/
      - ./django_app/logs/:/WaterSensor/logs/
    command: sh bin/django-start
    env_file: .env
    restart: always
    expose:
      - "${DJANGO_PORT:-8000}"
    ports:
      - ${DJANGO_PORT:-8000}:8000
    networks:
      - app_net
```

Facing same behavior on arm32v7/python:3.8-slim-buster and arm32v7/python:3.8-slim-buster but not on my windows 10 virtualenv
