### ISSUE TITLE
python:slim-bullseye – Is affected by CVE-2005-2541

### ISSUE THREAD

**Issue by guilledipa** [docker-library/python#751]
Hey folks,

When running:

```
gcloud artifacts docker images scan docker.io/library/python:slim-bullseye
```

The following `severity: CRITICAL` vulnerability is being reported:

```
---
createTime: '2022-08-19T16:55:12.125386Z'
kind: VULNERABILITY
name: projects/gkeconfluence-gcr/locations/us/occurrences/f342fbbd-429a-47f6-90f1-b3d4ac510114
noteName: projects/goog-vulnz/notes/CVE-2005-2541
resourceUri: docker.io/library/python:3.8.13-slim-bullseye
updateTime: '2022-08-19T16:55:12.125386Z'
vulnerability:
  cvssScore: 10.0
  effectiveSeverity: LOW
  longDescription: Tar 1.15.1 does not properly warn the user when extracting setuid
    or setgid files, which may allow local users or remote attackers to gain privileges.
  packageIssue:
  - affectedCpeUri: cpe:/o:debian:debian_linux:11
    affectedPackage: tar
    affectedVersion:
      fullName: 1.34+dfsg-1
      kind: NORMAL
      name: 1.34+dfsg
      revision: '1'
    effectiveSeverity: LOW
    fixedCpeUri: cpe:/o:debian:debian_linux:11
    fixedPackage: tar
    fixedVersion:
      kind: MAXIMUM
  relatedUrls:
  - label: More Info
    url: https://security-tracker.debian.org/tracker/CVE-2005-2541
  - label: More Info
    url: https://nvd.nist.gov/vuln/detail/CVE-2005-2541
  - label: More Info
    url: https://access.redhat.com/security/cve/CVE-2005-2541
  severity: CRITICAL
  shortDescription: CVE-2005-2541
```
